service: shree-shyam-sevak

frameworkVersion: '3'

provider:
  name: aws
  region: ap-south-1
  runtime: provided.al2
  environment:
    APP_ENV: ${sls:stage}
    APP_NAME: ${ssm:/shreeshyamsevak/${sls:stage}/APP_NAME}
    APP_STORAGE: /tmp
    APP_KEY: ${ssm:/shreeshyamsevak/${sls:stage}/APP_KEY}
    APP_DEBUG: ${ssm:/shreeshyamsevak/${sls:stage}/APP_DEBUG}
    ASSET_URL: ${ssm:/shreeshyamsevak/${sls:stage}/ASSET_URL}
    APP_URL: ${ssm:/shreeshyamsevak/${sls:stage}/APP_URL}

    
    VIEW_COMPILED_PATH: ${ssm:/shreeshyamsevak/${sls:stage}/VIEW_COMPILED_PATH}
    CACHE_PATH: ${ssm:/shreeshyamsevak/${sls:stage}/CACHE_PATH}
    LOG_PATH: ${ssm:/shreeshyamsevak/${sls:stage}/LOG_PATH}
    DEBUGBAR_ENABLED: false

    # App
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    APP_FAKER_LOCALE: en_US
    APP_MAINTENANCE_STORE: database
    BCRYPT_ROUNDS: 12

    # Logging
    LOG_CHANNEL: errorlog
    LOG_LEVEL: warning

    # Session
    SESSION_DRIVER: ${ssm:/shreeshyamsevak/${sls:stage}/SESSION_DRIVER}
    SESSION_LIFETIME: 120
    SESSION_ENCRYPT: false
    SESSION_PATH: /
    SESSION_DOMAIN: null
    SESSION_SAME_SITE: none
    SESSION_SECURE_COOKIE: true

    # Database
    DB_CONNECTION: ${ssm:/shreeshyamsevak/${sls:stage}/DB_CONNECTION}
    DB_HOST: ${ssm:/shreeshyamsevak/${sls:stage}/DB_HOST}
    DB_PORT: ${ssm:/shreeshyamsevak/${sls:stage}/DB_PORT}
    DB_DATABASE: ${ssm:/shreeshyamsevak/${sls:stage}/DB_DATABASE}
    DB_USERNAME: ${ssm:/shreeshyamsevak/${sls:stage}/DB_USERNAME}
    DB_PASSWORD: ${ssm:/shreeshyamsevak/${sls:stage}/DB_PASSWORD}

    # Cache / Queue
    CACHE_DRIVER: ${ssm:/shreeshyamsevak/${sls:stage}/CACHE_DRIVER}
    DYNAMODB_CACHE_TABLE: ${ssm:/shreeshyamsevak/${sls:stage}/DYNAMODB_CACHE_TABLE}
    QUEUE_CONNECTION: ${ssm:/shreeshyamsevak/${sls:stage}/QUEUE_CONNECTION}
    SQS_PREFIX: ${ssm:/shreeshyamsevak/${sls:stage}/SQS_PREFIX}
    SQS_QUEUE: ${ssm:/shreeshyamsevak/${sls:stage}/SQS_QUEUE}

    # Mail
    MAIL_MAILER: ${ssm:/shreeshyamsevak/${sls:stage}/MAIL_MAILER}
    MAIL_HOST: ${ssm:/shreeshyamsevak/${sls:stage}/MAIL_HOST}
    MAIL_PORT: ${ssm:/shreeshyamsevak/${sls:stage}/MAIL_PORT}
    MAIL_USERNAME: ${ssm:/shreeshyamsevak/${sls:stage}/MAIL_USERNAME}
    MAIL_PASSWORD: ${ssm:/shreeshyamsevak/${sls:stage}/MAIL_PASSWORD}
    MAIL_ENCRYPTION: ${ssm:/shreeshyamsevak/${sls:stage}/MAIL_ENCRYPTION}
    MAIL_FROM_ADDRESS: ${ssm:/shreeshyamsevak/${sls:stage}/MAIL_FROM_ADDRESS}
    MAIL_FROM_NAME: ${ssm:/shreeshyamsevak/${sls:stage}/MAIL_FROM_NAME}

    # Filesystem / S3
    FILESYSTEM_DRIVER: ${ssm:/shreeshyamsevak/${sls:stage}/FILESYSTEM_DRIVER}
    AWS_BUCKET: ${ssm:/shreeshyamsevak/${sls:stage}/AWS_BUCKET}
    AWS_URL: ${ssm:/shreeshyamsevak/${sls:stage}/AWS_URL}
    AWS_DEFAULT_REGION: ap-south-1

  iam:
    role:
      statements:
        # DynamoDB permissions
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:ap-south-1:*:table/shree-shyam-sevak-cache-*

        # SQS permissions
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - arn:aws:sqs:ap-south-1:*:shree-shyam-sevak-queue-${sls:stage}

        # S3 permissions
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::${ssm:/shreeshyamsevak/${sls:stage}/AWS_BUCKET}/*  

plugins:
  - ./vendor/bref/bref

package:
  exclude:
    - public/assets/**
    - public/fonts/**
    - public/webfonts/**
    - public/js/**
    - public/img/**
    - public/images/**
    - public/front_landing/**
    - public/css/**
    - public/mix-manifest.json
    - public/favicon.ico

functions:
  web:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-82-fpm}
    events:
      - httpApi: '*'

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: shree-shyam-sevak-queue-${sls:stage}

    CacheTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain   # <---- important
      UpdateReplacePolicy: Retain
      Properties:
        TableName: shree-shyam-sevak-cache-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST