name: Deploy Laravel to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Rsync code
        run: |
          rsync -avz --delete --exclude='.git' --exclude='node_modules' ./ ubuntu@${{ secrets.EC2_HOST }}:/var/www/shreeshyamsevak

      - name: Run deploy script
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "bash /home/ubuntu/fetch_env.sh prod"
